/*Nick Nowak
 March 22, 2017
 This program is designed to put a smile on the user's face by displaying an a 
 a personalized output based on their birthday.
 */

/**
 *
 * @author ninow1566
 */
public class Unit2AcitivityBirthdayGUI extends javax.swing.JFrame {

    /**
     * Creates new form Unit2AcitivityBirthdayGUI
     */
    public Unit2AcitivityBirthdayGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BirthdayPanel = new javax.swing.JPanel();
        BirthdayLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        NameInput = new javax.swing.JTextField();
        DateLabel = new javax.swing.JLabel();
        DateInput = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        Output1 = new javax.swing.JLabel();
        EmojiOutput = new javax.swing.JLabel();
        Output2 = new javax.swing.JLabel();
        BirthdayMenu = new javax.swing.JMenuBar();
        BirthdayMenu1 = new javax.swing.JMenu();
        BirthdayMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BirthdayPanel.setBackground(new java.awt.Color(255, 51, 51));
        BirthdayPanel.setForeground(new java.awt.Color(255, 51, 51));

        BirthdayLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BirthdayLabel.setForeground(new java.awt.Color(255, 255, 255));
        BirthdayLabel.setText("HAPPY BIRTHDAY!");

        NameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameLabel.setText("Please Enter Your Name:");

        NameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameInputActionPerformed(evt);
            }
        });

        DateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DateLabel.setForeground(new java.awt.Color(255, 255, 255));
        DateLabel.setText("Please Enter Your Date Of Birth");

        DateInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateInputActionPerformed(evt);
            }
        });

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        Output1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Output1.setForeground(new java.awt.Color(255, 255, 255));
        Output1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        EmojiOutput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unit/pkg2/activity/birthday/x1f389.png.pagespeed.ic.FkjckyE3hU.png"))); // NOI18N
        EmojiOutput.setText("jLabel5");

        Output2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Output2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout BirthdayPanelLayout = new javax.swing.GroupLayout(BirthdayPanel);
        BirthdayPanel.setLayout(BirthdayPanelLayout);
        BirthdayPanelLayout.setHorizontalGroup(
            BirthdayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BirthdayPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BirthdayLabel)
                .addGap(162, 162, 162))
            .addGroup(BirthdayPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(BirthdayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BirthdayPanelLayout.createSequentialGroup()
                        .addComponent(EmojiOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(BirthdayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Output1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Output2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubmitButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(BirthdayPanelLayout.createSequentialGroup()
                        .addComponent(NameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NameInput))
                    .addGroup(BirthdayPanelLayout.createSequentialGroup()
                        .addComponent(DateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DateInput)))
                .addContainerGap())
        );
        BirthdayPanelLayout.setVerticalGroup(
            BirthdayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BirthdayPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BirthdayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BirthdayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameLabel))
                .addGap(18, 18, 18)
                .addGroup(BirthdayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateLabel))
                .addGroup(BirthdayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BirthdayPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(SubmitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Output1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Output2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BirthdayPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(EmojiOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        Output1.getAccessibleContext().setAccessibleName("jpanel1");

        BirthdayMenu1.setText("File");
        BirthdayMenu.add(BirthdayMenu1);

        BirthdayMenu2.setText("Edit");
        BirthdayMenu.add(BirthdayMenu2);

        setJMenuBar(BirthdayMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BirthdayPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BirthdayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameInputActionPerformed
        
    }//GEN-LAST:event_NameInputActionPerformed

    private void DateInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateInputActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
            String name = "";
        name = NameInput.getText();
        String birthday = "";
        birthday = DateInput.getText();
        Output1.setText("On " +birthday + " a great person was born! "); 
        Output2.setText("You " +name + " are an AMAZING person! ");
    }//GEN-LAST:event_SubmitButtonActionPerformed
    //Displays input information when submit button is clicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Unit2AcitivityBirthdayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Unit2AcitivityBirthdayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Unit2AcitivityBirthdayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Unit2AcitivityBirthdayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Unit2AcitivityBirthdayGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BirthdayLabel;
    private javax.swing.JMenuBar BirthdayMenu;
    private javax.swing.JMenu BirthdayMenu1;
    private javax.swing.JMenu BirthdayMenu2;
    private javax.swing.JPanel BirthdayPanel;
    private javax.swing.JTextField DateInput;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JLabel EmojiOutput;
    private javax.swing.JTextField NameInput;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel Output1;
    private javax.swing.JLabel Output2;
    private javax.swing.JButton SubmitButton;
    // End of variables declaration//GEN-END:variables
}
